layer: top

# river/tags:
#   num-tags: 6

custom/launcher:
  format: 'ïŒƒ '
  on-click:
    gamemoderun fuzzel

cpu:
  interval: 15
  format: ï‹› {}%
  max-length: 10
memory:
  interval: 30
  format: ïƒ‰ {}%
  max-length: 10
temperature:
  # thermal-zone: 2
  hwmon-path: /sys/class/hwmon/hwmon2/temp1_input
  critical-threshold: 90
  format-critical: "{icon} {temperatureC}Â°C"
  format: "{icon} {temperatureC}Â°C"
  format-icons:
    - ï«
    - ï‹‰
    - ï©
disk:
  interval: 30
  format: "ğŸ–´ {path} ({percentage_used}/{percentage_free})%"
  on-click: baobab

# custom/media:
#   interval: 30
#   format: '{icon} {}'
#   return-type: json
#   max-length: 20
#   format-icons:
#     spotify: 'ï†¼ '
#     default: 'ï¢… '
#   escape: true
#   exec: $HOME/.config/system_scripts/mediaplayer.py 2> /dev/null
#   on-click: playerctl play-pause

network:
  interface: wlan0
  format: '{ifname}'
  format-wifi: "{essid} ({signalStrength}%) ï‡« "
  format-ethernet: "{ifname} ïƒ "
  format-disconnected: "ï² "
  tooltip-format: "{ifname}"
  tooltip-format-wifi: "{essid} ({signalStrength}%) ï‡« "
  tooltip-format-ethernet: "{ifname} ïƒ "
  tooltip-format-disconnected: "Disconnected"
  max-length: 50
  on-click: iwgtk

tray:
  icon-size: 21
  spacing: 10

# backlight:
#   device: "intel_backlight"
#   format: "{percent}% {icon}"
#   format-icons:
#     - ï†…
#     - ï„‘

backlight:
  tooltip: false
  format: ïƒ« {}%
  interval: 1
  on-scroll-up: light -A 5
  on-scroll-down: light -U 5

pulseaudio:
  scroll-step: 5
  format: "{volume}% {icon}"
  format-bluetooth: "{volume}% {icon} ïŠ”"
  # ïš©
  format-bluetooth-muted: "0%  {icon} ïŠ”"
  format-muted: "ï€¦"
  format-source: ""
  format-source-muted: ï„±
  format-icons:
    headphone: ï€¥
    hands-free: ï–
    headset: ï–
    phone: ï‚•
    portable: ï‚•
    car: ï†¹
    hdmi: ï‰¬
    default:
      - ï€¦
      - ï€§
      - ï€¨
  ignored-sinks:
    - Easy Effects Sink
  on-click: pamixer --toggle-mute
  # pactl set-sink-mute @DEFAULT_SINK@ toggle
  on-click-right: pavucontrol

clock:
  format: '{:ï€— %I:%M %p ğŸ—“ %d/%m/%Y}'
  on-click:
    gamemoderun wldash

# battery:
#   # bat: BAT2
#   interval: 60
#   states:
#     good: 95
#     warning: 30
#     critical: 15
#   max-length: 25
#   format: '{icon}  {capacity}%'
#   format-charging: "ï‡¦ {capacity}%"
#   format-plugged: "ï‡¦ {capacity}%"
#   format-alt: '{time} {icon}'
#   format-icons:
#     - ï‰„
#     - ï‰ƒ
#     - ï‰‚
#     - ï‰
#     - ï‰€

custom/power:
  format: 'ï€‘ '
  on-click:
    gamemoderun waylogout
      --hide-cancel
      --screenshots
      --font="Baloo 2"
      --fa-font="Font Awesome 6 Free"
      --effect-blur=7x5
      --indicator-thickness=20
      --ring-color=888888aa
      --inside-color=88888866
      --text-color=eaeaeaaa
      --line-color=00000000
      --ring-selection-color=33cc33aa
      --inside-selection-color=33cc3366
      --text-selection-color=eaeaeaaa
      --line-selection-color=00000000
      --lock-command="echo lock"
      --logout-command="echo logout"
      --suspend-command="echo suspend"
      --hibernate-command="echo hibernate"
      --poweroff-command="echo poweroff"
      --reboot-command="echo reboot"
      --switch-user-command="echo switch"
      --selection-label

custom/updates:
  format: '{} Update(s)'
  exec: checkupdates | wc -l
  exec-if: '[[ $(checkupdates | wc -l) != 0 ]]'
  interval: 15
  on-click: 'wezterm -e paru -Syyu && notify-send ''The system has been updated'' '

# custom/wallpaper:
#   format: 'ï€¾ '
#   on-click: bash ~/.config/system_scripts/pkill_bc

custom/shade:
  format: '{}'
  exec: "
    if [[ $(hyprshade ls | grep '^* blue-light-filter' | wc -l) == 1 ]]
    ; then echo 'ï° '
    ; else echo 'ï® '
    ; fi"
  on-click: "
    if [[ $(hyprshade ls | grep '^* blue-light-filter' | wc -l) == 1 ]]
    ; then hyprshade on vibrance
    ; else hyprshade on blue-light-filter
    ; fi"
  interval: 15

modules-left:
  - custom/launcher
  - cpu
  - memory
  - temperature
  - disk

hyprland/workspaces:
  format: "{name}"

modules-center:
  # - river/tags
  - hyprland/workspaces

modules-right:
  # - custom/wallpaper
  # - custom/media
  - custom/updates
  - network
  - tray
  - backlight
  - custom/shade
  - clock
  - pulseaudio
  # - battery
  - custom/power
